version: '3.7'

services:
  bxradio-client:
    build:
      context: .
      dockerfile: ./src/client/Dockerfile
    ports:
      - 80:80
  bxradio-server:
    build:
      context: .
      dockerfile: ./src/server/Dockerfile
    ports:
      - 8080:80
  slackspot:
    image: slackspot
    ports:
      - 8081:80
      - 8443:443

